plugins:
  - jemoji
  - jekyll-remote-theme
# remote_theme: jekyll/minima

title: sotanishy's competitive programming library
author: sotanishy
description: sotanishy's code snippets for competitive programming

exclude: ["icpc-document"]

header_pages:
  - null
